### ISSUE TITLE
PMX Library for PythonからPMXを動かす

### ISSUE THREAD

**Issue by Yusuke-Yamasaki-555** [Yusuke-Yamasaki-555/sustaina-op_soft_dev_test#2]
[https://kondo-robot.com/faq/pmx-library-for-python](https://kondo-robot.com/faq/pmx-library-for-python)

サンプルコードがあるから、それを一通り動かしてみる。

まず、環境はWindowsでやってみる。よくわからなくなったら、Linux系でやる。

（来週やる）

**Comment by Yusuke-Yamasaki-555** [comment]
まずはWindowsで試してみる。

* python3.8のinstall (microsoft store)
* pip install pyserial

* MemREADから、説明に従ってやってみる
https://kondo-robot.com/faq/pmx-servo-tutorial-pc2

* WSLから使いたいので、以下に従ってデバイスを読めるようにする。https://learn.microsoft.com/ja-jp/windows/wsl/connect-usb

**Comment by HarukiOgawa1** [comment]
MemREAD_Sample20231023.py の26行目の「Pmxのライブラリのパスを登録」をos.path.joinに変更
提供されているものだとパスが登録されず，以下のエラーが発生する．
```
Traceback (most recent call last):
  File "/home/harukiogawa/Kondou/PmxPythonLibV1_0_2_0/sample/MemREAD_Sample20231023.py", line 30, in <module>
    from PmxPySerialClass  import PmxPySerialClass  # pySerialでPMXを通信するクラスをつかるようにする
ModuleNotFoundError: No module named 'PmxPySerialClass'
```
-----
書き換えると
```
pmxLibPath = parent_dir + '\PmxLib'
```
↓
```
pmxLibPath = os.path.join(parent_dir, 'PmxLib')
```

**Comment by Yusuke-Yamasaki-555** [comment]
sampleプログラム”MemREAD_Sample20231023.py”の実行ができた。
単に設定周りを読むだけなので、モータの駆動はしていない。
以下、出力結果：
```
TryOPEN
/dev/ttyUSB0
Serial Connect success
300番地(現在位置)から6byte読み出します(返り値はbytes型)
0x0 b'a\x16\xff\xff\x0b\x00'
現在位置 5729
2byte(signed)の位置データを取得します
0x0 57.29 [°]
2byte(unsigned)の電圧データを取得します
0x0 13.365 [V]
4byte(unsigned)の位置制御のPゲインを取得します
0x0 3000
1byte(unsigned)のトルクスイッチの状態を取得します
0x0 1
トルクスイッチの状態を読み出します
0x0 1
エラーステータス(400番地から6byte)からエラー情報を読み出します
エラー情報を読み出すと解除されます
0x0 [0, 0, 0, 0]
```

基本的に、上記のセットアップとコード書き換えでできた。
以下、設定：
```
comName = "/dev/ttyUSB0"
pmxBaudrate = 1000000
ServoID = 16
```

**Comment by HarukiOgawa1** [comment]
Sampleプログラム"MemWRITE_Sample20231023.py"の実行ができた
（トルクスイッチのON/OFFのみ），電圧等はコメントアウト

各関数の引数については以下に書いてある．
https://kondo-robot.com/faq/pmx-servo-tutorial-pc3

出力結果
```
TryOPEN
/dev/ttyUSB0
Serial Connect success
トルクスイッチの状態を読み出します　　# 書き込み前のトルクスイッチの状態
0x0 1
トルクスイッチに2(Free)を書き込みます
0x0
トルクスイッチを読み出します
0x0 2
```

**Comment by Yusuke-Yamasaki-555** [comment]
設定値の変更（2024/7/19 205 ID16 , 7/21 201 ID06）：
- 入力電圧最小時の出力％値：80 -> 100 [%]
- 入力電圧最大値設定：15000 -> 16000 [mV]
- 入力電圧最大時の出力％値：80 -> 100 [%]

サンプル実行時に上限に触れて停止するのを避けるため

**Comment by Yusuke-Yamasaki-555** [comment]
https://kondo-robot.com/faq/pmx-servo-tutorial-pc4-1

これに沿ってモータを位置制御できた。
コード改変はしていない。

https://github.com/user-attachments/assets/d162e3bd-da85-4e58-8ba5-a9ea92f6e364

**Comment by HarukiOgawa1** [comment]
https://github.com/Yusuke-Yamasaki-555/sustaina-op2_soft_dev_test/issues/2#issuecomment-2431054884 の追記
位置制御のサンプルを試す際に以下のパラメータの設定の最大値を上げないとモータが回らない
(ロボットに取り付ける際は設定しないといけないパラメータ)
![スクリーンショット 2024-10-23 161736](https://github.com/user-attachments/assets/c54c34f6-0b43-4610-826f-3426be80e854)

**Comment by HarukiOgawa1** [comment]
PMXをデイジーチェーンで二つ同時に位置制御した
変更点
ServoIDをServoID1, ServoID2に振り分けて，以下のように複製する
```
    status = pmx.setControlMode(ServoID1, controlMode, writeOpt=0x01)
    status = pmx.setControlMode(ServoID2, controlMode, writeOpt=0x01)
```

https://youtu.be/oeYNsZZRCOE

**Comment by Yusuke-Yamasaki-555** [comment]
https://kondo-robot.com/faq/pmx-servo-tutorial-pc4-2
https://www.kondokagaku.jp/wp_mn/archives/1144#commandexplanation

MotortWRITE_PosTimeMove_Sample20231023.pyで、位置制御＆移動時間を試すことができた。
- PMXはメモリマップからして速度を入力として回転速度と回転位置を同時に制御することはできず、その代わりに目標関節角度までの移動時間を指定することができる。 
  - 速度制御となると、無限回転での回転速度を制御するものになる。車輪型ロボットには使えるだろうね。

**Comment by Yusuke-Yamasaki-555** [comment]
library の sample で試したいことは一通り済んだので、この issue は close する。
